### ISSUE TITLE
找不到word2vec与t_tr

### ISSUE THREAD

**Issue by yaleimeng** [qiangsiwei/bert_distill#1]
运行test.py时报错，No such file or directory: 'data/cache/word2vec'
找了一个200维的明文词向量改了名字算是糊弄过去了。utils里还改了一下维度。

然后运行distll、small时报错， No such file or directory: 'data/cache/t_tr'
这个又是什么文件？能否提供下载？

**Comment by qiangsiwei** [comment]
已添加数据

**Comment by yaleimeng** [comment]
感谢分享，希望多多交流
